import { createRequire } from "node:module";

export const { name: PACKAGE_NAME, version: PACKAGE_VERSION } =
  createRequire(import.meta.url)("../package.json");

export const CLI_NAME = "spec-guardrails";
export const DISPLAY_NAME = "Spec Guardrails";
export const NPX = (command) => `npx ${PACKAGE_NAME}${command ? ` ${command}` : ""}`;

const REPO_RAW_BASE =
  "https://raw.githubusercontent.com/luizssantiago92/spec-guardrails";

/** Assets are fetched from the tag matching the installed CLI version. */
export const PINNED_REF = `v${PACKAGE_VERSION}`;

/** Used only when the pinned tag is not published yet. */
export const FALLBACK_REF = "main";

export const REPO_RAW_URL = `${REPO_RAW_BASE}/${PINNED_REF}`;

export const FALLBACK_REPO_URL = `${REPO_RAW_BASE}/${FALLBACK_REF}`;

export const SKILL_DIRS = [
  ".cursor/skills",
  ".claude/skills",
  ".github/skills",
  ".codex/skills",
];

export const CURSOR_RULES_DIR = ".cursor/rules";

export const REFERENCES_SUBDIR = "references";

export const GUARDRAILS_SCRIPTS_DIR = ".specs/guardrails/scripts";

/** @type {{ file: string, remotePath: string }[]} */
export const SKILL_ASSETS = [
  {
    file: "agent-architecture.md",
    remotePath: "skills/agent-architecture.md",
  },
  {
    file: "engineering-standards.md",
    remotePath: "skills/engineering-standards.md",
  },
  {
    file: "security-review.md",
    remotePath: "skills/security-review.md",
  },
  {
    file: "appsec.md",
    remotePath: "skills/appsec.md",
  },
  {
    file: "qa-strategy.md",
    remotePath: "skills/qa-strategy.md",
  },
  {
    file: "code-simplify.md",
    remotePath: "skills/code-simplify.md",
  },
  {
    file: "ship-ready.md",
    remotePath: "skills/ship-ready.md",
  },
  {
    file: "git-handoff.md",
    remotePath: "skills/git-handoff.md",
  },
  {
    file: "task-graph-engineering.md",
    remotePath: "skills/task-graph-engineering.md",
  },
];

/** Phase procedures loaded on demand by the hub skill. */
/** @type {{ file: string, remotePath: string }[]} */
export const REFERENCE_ASSETS = [
  { file: "explore.md", remotePath: "skills/references/explore.md" },
  { file: "project-init.md", remotePath: "skills/references/project-init.md" },
  { file: "constitution.md", remotePath: "skills/references/constitution.md" },
  { file: "specify.md", remotePath: "skills/references/specify.md" },
  { file: "discuss.md", remotePath: "skills/references/discuss.md" },
  { file: "design.md", remotePath: "skills/references/design.md" },
  { file: "tasks.md", remotePath: "skills/references/tasks.md" },
  { file: "analyze.md", remotePath: "skills/references/analyze.md" },
  { file: "implement.md", remotePath: "skills/references/implement.md" },
  { file: "validate.md", remotePath: "skills/references/validate.md" },
  { file: "converge.md", remotePath: "skills/references/converge.md" },
  { file: "archive.md", remotePath: "skills/references/archive.md" },
  { file: "memory.md", remotePath: "skills/references/memory.md" },
  { file: "quick-mode.md", remotePath: "skills/references/quick-mode.md" },
  { file: "context-limits.md", remotePath: "skills/references/context-limits.md" },
  { file: "lessons.md", remotePath: "skills/references/lessons.md" },
  { file: "sub-agents.md", remotePath: "skills/references/sub-agents.md" },
];

/** Deterministic gates executed with python3. */
/** @type {{ file: string, remotePath: string }[]} */
export const SCRIPT_ASSETS = [
  { file: "_common.py", remotePath: "scripts/_common.py" },
  { file: "validate_spec.py", remotePath: "scripts/validate_spec.py" },
  { file: "validate_tasks.py", remotePath: "scripts/validate_tasks.py" },
  { file: "validate_state.py", remotePath: "scripts/validate_state.py" },
  { file: "validate_traceability.py", remotePath: "scripts/validate_traceability.py" },
  { file: "validate_quick.py", remotePath: "scripts/validate_quick.py" },
  { file: "analyze_artifacts.py", remotePath: "scripts/analyze_artifacts.py" },
  { file: "check_commit.py", remotePath: "scripts/check_commit.py" },
  { file: "lessons.py", remotePath: "scripts/lessons.py" },
  { file: "loop_plan.py", remotePath: "scripts/loop_plan.py" },
  { file: "memory_index.py", remotePath: "scripts/memory_index.py" },
  { file: "memory_query.py", remotePath: "scripts/memory_query.py" },
];

/** @type {{ file: string, remotePath: string }[]} */
export const RULE_ASSETS = [
  {
    file: "engineering-baseline.mdc",
    remotePath: "rules/engineering-baseline.mdc",
  },
];

export const STATE_HEADER = `# 📝 Project State & Decisions

## Active Feature
- Feature: —
- Phase: —
- Branch: —

## Next Step (single item)
- [ ] —

## Blockers
- none

## Deferred Ideas
- none

## Decisions
`;

export const LESSONS_HEADER = `# Lessons Learned

Generated by \`lessons.py\` from \`.specs/lessons.json\`. Do not edit this file.
A clean PASS records nothing. Only **confirmed** lessons below are guidance.
Inspect candidates with \`python3 .specs/guardrails/scripts/lessons.py list --status all\`.

- none yet
`;

export const CURSORRULES_MARKER_BEGIN = "<!-- SPEC-GUARDRAILS:BEGIN -->";

export const CURSORRULES_MARKER_END = "<!-- SPEC-GUARDRAILS:END -->";

/**
 * Prior product markers — recognized only so `install` can upgrade `.cursorrules`.
 * Runtime does not dual-path scripts under these names.
 */
export const LEGACY_CURSORRULES_MARKER_PAIRS = [
  ["<!-- SPEC-SEATBELT:BEGIN -->", "<!-- SPEC-SEATBELT:END -->"],
  ["<!-- AGENTIC-HARNESS:BEGIN -->", "<!-- AGENTIC-HARNESS:END -->"],
];

/** @deprecated Use LEGACY_CURSORRULES_MARKER_PAIRS */
export const LEGACY_CURSORRULES_MARKER_BEGIN = "<!-- AGENTIC-HARNESS:BEGIN -->";

/** @deprecated Use LEGACY_CURSORRULES_MARKER_PAIRS */
export const LEGACY_CURSORRULES_MARKER_END = "<!-- AGENTIC-HARNESS:END -->";

const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);

/**
 * Assets become executable gate scripts on disk, so the source has to be
 * trustworthy. Plain HTTP is rejected except against a local host, which the
 * test suite uses.
 *
 * @param {string} base
 * @returns {string} the validated base, without a trailing slash
 */
function assertAllowedAssetUrl(raw) {
  let url;

  try {
    url = new URL(raw);
  } catch {
    throw new Error(`Invalid guardrails asset URL: ${raw}`);
  }

  const isLocal = LOCAL_HOSTS.has(url.hostname);

  if (url.protocol === "https:" || (url.protocol === "http:" && isLocal)) {
    return url;
  }

  throw new Error(
    `Refusing to download guardrails assets over ${url.protocol}//${url.hostname} ` +
      "— only HTTPS sources are allowed. Guardrails assets include executable gate scripts.",
  );
}

export function assertSafeAssetBase(base) {
  assertAllowedAssetUrl(base);
  return base.replace(/\/+$/, "");
}

/**
 * Validate a full download URL (including path), including each redirect hop.
 * Returns the URL string unchanged when the scheme/host policy passes.
 * When `sourceUrl` is set (a redirect hop), the next URL must share that origin.
 *
 * @param {string} raw
 * @param {string} [sourceUrl] previous hop; cross-origin redirects are refused
 * @returns {string}
 */
export function assertSafeDownloadUrl(raw, sourceUrl) {
  assertAllowedAssetUrl(raw);

  if (sourceUrl) {
    const next = new URL(raw);
    const from = new URL(sourceUrl);
    if (next.origin !== from.origin) {
      throw new Error(
        `Refusing to follow a cross-origin redirect from ${from.origin} to ${next.origin}`,
      );
    }
  }

  return raw;
}

/** @returns {string | undefined} the override base, when one is configured */
export function resolveAssetOverride() {
  const override = process.env.SPEC_GUARDRAILS_REPO_URL;
  return override ? assertSafeAssetBase(override) : undefined;
}

/**
 * @param {string} remotePath
 * @param {string} [repoUrl]
 */
export function resolveAssetUrl(remotePath, repoUrl) {
  const base = assertSafeAssetBase(
    repoUrl ?? resolveAssetOverride() ?? REPO_RAW_URL,
  );
  return `${base}/${remotePath}`;
}
