import { featureOverview } from "./feature-overview.js";

/**
 * @param {Awaited<ReturnType<typeof featureOverview>>} overview
 * @returns {string}
 */
export function formatPrBody(overview) {
  const status = overview.status ?? {};
  const lines = [
    "## Summary",
    "",
    overview.goal
      ? overview.goal
      : `Feature **${overview.featureId}** — see traceability below.`,
    "",
    "## Spec Guardrails traceability",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Feature | \`${overview.featureId}\` |`,
    `| Phase | ${status.phase ?? "—"} |`,
    `| Validation | ${status.verdict ?? "—"} |`,
    "",
    "### REQ → task → evidence",
    "",
    "| REQ | Task(s) | Test evidence |",
    "| --- | --- | --- |",
  ];

  for (const row of overview.traceability ?? []) {
    const tasks = row.tasks?.length ? row.tasks.join(", ") : "—";
    const evidence = row.evidence ?? "—";
    lines.push(`| ${row.reqId} | ${tasks} | ${evidence} |`);
  }

  if (!overview.traceability?.length) {
    lines.push("| — | — | — |");
  }

  lines.push(
    "",
    "## Test plan",
    "",
    "- [ ] Project test suite / CI green",
    "- [ ] `validation.md` verdict PASS (independent verify)",
    "- [ ] Owner approved spec and tasks",
    "",
    "---",
    "_Generated by `feature-pr-body` from Spec Guardrails `feature-overview`._",
  );

  return `${lines.join("\n")}\n`;
}

/**
 * @param {string | undefined} featureArg
 * @returns {Promise<{ featureId: string, body: string }>}
 */
export async function featurePrBody(featureArg) {
  const overview = await featureOverview(featureArg, { write: false });
  return {
    featureId: overview.featureId,
    body: formatPrBody(overview),
  };
}
